

export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS'
export const ALL_ROOMS_FAILDED = 'ALL_ROOMS_FAILDED'


export const ROOMS_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOMS_DETAILS_FAILDED = 'ROOM_DETAILS_FAILDED'


export const CLEAR_ERROR = 'CLEAR_ERROR'